In [ ]:
import pandas as pd

PROCESSED_AGD_DATASET = pd.read_csv('PROCESSED_AGD_DATASET.csv')
PROCESSED_BENIGN_DATASET = pd.read_csv('PROCESSED_BENIGN_DATASET.csv')

In [ ]:
PROCESSED_BENIGN_DATASET.describe()

NameError: ignored

In [ ]:
PROCESSED_AGD_DATASET[PROCESSED_AGD_DATASET['agd_type'] == 'chinad'].describe()

       domain_len  ...  quad_gram_score_relative_to_en_words
count       256.0  ...                            256.000000
mean         16.0  ...                              0.016846
std           0.0  ...                              0.067383
min          16.0  ...                              0.000000
25%          16.0  ...                              0.000000
50%          16.0  ...                              0.000000
75%          16.0  ...                              0.000000
max          16.0  ...                              0.625000

[8 rows x 16 columns]

In [ ]:
PROCESSED_AGD_DATASET[PROCESSED_AGD_DATASET['agd_type'] == 'banjori'].describe()

       domain_len  ...  quad_gram_score_relative_to_en_words
count      1000.0  ...                           1000.000000
mean         26.0  ...                              3.766385
std           0.0  ...                              0.314081
min          26.0  ...                              3.538462
25%          26.0  ...                              3.538462
50%          26.0  ...                              3.653846
75%          26.0  ...                              3.846154
max          26.0  ...                              5.961538

[8 rows x 16 columns]

In [ ]:
PROCESSED_AGD_DATASET[PROCESSED_AGD_DATASET['agd_type'] == 'newgoz'].describe()

        domain_len  ...  quad_gram_score_relative_to_en_words
count  1000.000000  ...                           1000.000000
mean     25.942000  ...                              0.012881
std       1.063846  ...                              0.071804
min      23.000000  ...                              0.000000
25%      25.000000  ...                              0.000000
50%      26.000000  ...                              0.000000
75%      27.000000  ...                              0.000000
max      28.000000  ...                              1.240000

[8 rows x 16 columns]

In [ ]:
PROCESSED_AGD_DATASET[PROCESSED_AGD_DATASET['agd_type'] == 'necurs'].describe()

        domain_len  ...  quad_gram_score_relative_to_en_words
count  2048.000000  ...                           2048.000000
mean     13.865234  ...                              0.070562
std       4.367397  ...                              0.331784
min       7.000000  ...                              0.000000
25%      10.000000  ...                              0.000000
50%      14.000000  ...                              0.000000
75%      18.000000  ...                              0.000000
max      21.000000  ...                             10.142857

[8 rows x 16 columns]